logger:
  #Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
  consoleShow: true
  consoleLevel:  7
  fileWrite:  false
  fileLevel:  7
  multiFileWrite: false
  multiFileLevel: 7

rpcServer:
  serverName: "logic-rpc"
  registerPlugin: "multiple"
  registerServers:
    - "127.0.0.1:2379"
  basePath: "example-project"
  addr: ""
  port: 8899
  pprof: 18899

tracer:
  openTrace: true
  traceName: "logic-rpc"
  host: "127.0.0.1:6831"

